### ISSUE TITLE
你好可以增加下nanoserver的镜像吗

### ISSUE THREAD

**Issue by hongliuyi** [newbe36524/Newbe.McrMirror#11]
我目前需要用到如下两个，已经搞了两天了。麻烦你啦，十分感谢！

mcr.microsoft.com/dotnet/core/aspnet:3.1-nanoserver-1903
mcr.microsoft.com/dotnet/core/sdk:3.1-nanoserver-1903

**Comment by newbe36524** [comment]
你已经尝试过什么方法了，请罗列一下。

**Comment by hongliuyi** [comment]
1.Dock设置镜像加速
试过如下几个
"http://f1361db2.m.daocloud.io"
"https://pee6w651.mirror.aliyuncs.com"
 "https://registry.docker-cn.com“
速度大概 20k/秒，下载8M左右就超时退出了
2.本仓库Newbe.McrMirror，但是没有找到相关的Tag。
3.使用翻墙，直接trojan-qt5 翻墙看youtube视频都不卡，但是下载微软这两个镜像速度就是不行，有可能是我配置问题。

**Comment by hongliuyi** [comment]
![image](https://user-images.githubusercontent.com/33167076/93837118-93f8eb00-fcb7-11ea-9813-93ba78f7487f.png)
![image](https://user-images.githubusercontent.com/33167076/93837348-58aaec00-fcb8-11ea-9c62-5b7c3681f8cc.png)

应该是我这边网络有问题吧。
刚刚用阿里云镜像加速，下载虽然不快，但是可以正常下载。这速度估计要下载2个小时。
我用的是300M宽带。

**Comment by newbe36524** [comment]
1. mcr 实质上是一个独立的服务器，不会从 mirror 走，会直接走 azure 上的服务器。
2. 我们正在尝试推送这些镜像

**Comment by newbe36524** [comment]
@hongliuyi 刚刚推送了一个，试一下拉这个  registry.cn-hangzhou.aliyuncs.com/newbe36524/aspnet:3.1-nanoserver-1903

**Comment by hongliuyi** [comment]
@newbe36524   收到，十分感谢。我现在外面出差去了，要晚上回去家里才能试一下。Thanks a lot!

**Comment by hongliuyi** [comment]
![image](https://user-images.githubusercontent.com/33167076/93952217-e2bb8900-fd7a-11ea-8b2e-f1c64a2daf06.png)
已经成功拉取了，谢谢！

**Comment by newbe36524** [comment]
@all-contributors please add @hongliuyi for bug
