### ISSUE TITLE
请问能帮忙新增一下vscode/devcontainers的镜像

### ISSUE THREAD

**Issue by zengzhengrong** [newbe36524/Newbe.McrMirror#12]
找了很久没找到

**Comment by newbe36524** [comment]
干啥用的？详细说一下

**Comment by zengzhengrong** [comment]
@newbe36524  
用于在容器里做开发
vscode 一个remote container 插件会生成一个dockerfile，里面的基础镜像就是用mcr的

**Comment by newbe36524** [comment]
所以你只需要 base 的那个就可以了？ 特种语言的tag很多耶。全部的话，我需要看看怎么写脚本。

**Comment by zengzhengrong** [comment]
@newbe36524 
我大概需要一些主流语言，java go python php rust dart javascript

**Comment by newbe36524** [comment]
@all-contributors please add @zengzhengrong for idea

**Comment by newbe36524** [comment]
@zengzhengrong 按照 readme的新说明试一下

**Comment by zengzhengrong** [comment]
楼主  能帮我 补个 mcr.microsoft.com/vscode/devcontainers/typescript-node镜像吗

**Comment by newbe36524** [comment]
readme 下面不是写了有吗

**Comment by zengzhengrong** [comment]
抱歉没看到
