### ISSUE TITLE
mcr.microsoft.com/dotnet/core/sdk:3.1-buster

### ISSUE THREAD

**Issue by WuJieFly** [newbe36524/Newbe.McrMirror#18]
![image](https://user-images.githubusercontent.com/11804903/99778532-c788b200-2b4e-11eb-9884-782d202311f6.png)

**Comment by newbe36524** [comment]
mcr.microsoft.com/dotnet/sdk:3.1-buster  新的已经没有 core 了

**Comment by newbe36524** [comment]
看 readme 列表中包含的 tag
