### ISSUE TITLE
请帮忙增加 windows 系列镜像

### ISSUE THREAD

**Issue by FangPengbo** [newbe36524/Newbe.McrMirror#25]
docker pull  mcr.microsoft.com/windows:20H2

**Comment by newbe36524** [comment]
这个吗？ 
https://hub.docker.com/_/microsoft-windows

**Comment by newbe36524** [comment]
@all-contributors please add @FangPengbo for idea

**Comment by newbe36524** [comment]
@all-contributors please add @WeihanLi for idea
