### ISSUE TITLE
docker-mcr -i  mcr.microsoft.com/vscode/devcontainers/cpp:0-debian-11 拉取无反应

### ISSUE THREAD

**Issue by kingui1106** [newbe36524/Newbe.McrMirror#53]
docker-mcr -i mcr.microsoft.com/vscode/devcontainers/cpp:0-debian-11
而且官方remote-cpp的例子地址好像换成了  `mcr.microsoft.com/devcontainers/cpp:0-debian-11`
两个地址应该都能用

**Comment by newbe36524** [comment]
修复好了，请再试一下
