### ISSUE TITLE
请增加 mssql 系列镜像

### ISSUE THREAD

**Issue by fisherwei** [newbe36524/Newbe.McrMirror#8]
https://hub.docker.com/_/microsoft-mssql-server

**Comment by newbe36524** [comment]
see and working

**Comment by newbe36524** [comment]
@fisherwei 镜像已经推送，目前只能通过文档中的方法二或者三进行获取加速， docker-mcr 暂不支持。需等待一下版本。 
目前的地址形如 ： registry.cn-hangzhou.aliyuncs.com/newbe36524/server

**Comment by newbe36524** [comment]
@all-contributors please add @fisherwei for report

**Comment by newbe36524** [comment]
@all-contributors please add @fisherwei for data

**Comment by newbe36524** [comment]
@all-contributors please add @fisherwei for idea

**Comment by newbe36524** [comment]
经测试，docker-mcr 已经能够正常加速下载。腾讯云仍然需要另外处理.

**Comment by newbe36524** [comment]
@all-contributors please add @fisherwei for bug
